language: go

go:
  - 1.9
  - 1.10.x
  - tip

env:
  global:
    - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -vendor-only

#before_script:
#  # coverage reporter
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build

script:
#  - go test -v -race -coverprofile=coverage.out -covermode=atomic
  - go test -v -race

#after_script:
#  - ./cc-test-reporter format-coverage -t gocov coverage.out
#  - ./cc-test-reporter upload-coverage
